### ISSUE TITLE
Sorry, you need to login first to access this service.

### ISSUE THREAD

**Issue by Krasuszz** [cssxsh/mirai-new-bing#1]
**参数配置：**
除了使用http代理外全部默认，cookie正常填写

**报错信息：**

```
java.lang.IllegalStateException: Sorry, you need to login first to access this service.
        at mirai-new-bing-0.1.0.mirai2.jar//xyz.cssxsh.bing.NewBingClient.create$suspendImpl(NewBingClient.kt:73)
        at mirai-new-bing-0.1.0.mirai2.jar//xyz.cssxsh.bing.NewBingClient$create$1.invokeSuspend(NewBingClient.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at mirai-new-bing-0.1.0.mirai2.jar[private]//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by cssxsh** [comment]
> java.lang.IllegalStateException: Sorry, you need to login first to access this service.

https://www.bing.com/new

你没有登录一下激活 new bing 吗

**Comment by Krasuszz** [comment]
> 

我的mcl部署在服务器上，然后在个人电脑上登录了newbing并抓取了cookie，我需要在服务器上登录bing吗

**Comment by cssxsh** [comment]
你可以先拿 

https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma?utm_source=chrome-ntp-icon

测试一下你的账号有没有开启 New Bing 功能

**Comment by Krasuszz** [comment]
> 你可以先拿
> 
> https://chrome.google.com/webstore/detail/chathub-all-in-one-chatbo/iaakpnchhognanibcahlpcplchdfmgma?utm_source=chrome-ntp-icon
> 
> 测试一下你的账号有没有开启 New Bing 功能

尝试了，可以使用这个插件与New Bing交流

**Comment by cssxsh** [comment]
那你重新提取一下 New Bing 网页 Cookie 
最关键是 _U 这个 Cookie

**Comment by Krasuszz** [comment]
> 那你重新提取一下 New Bing 网页 Cookie 最关键是 `_U` 这个 Cookie

报错还是存在
我尝试了第一次登录和后续自动登录的cookie，都不行
这是其中一次的cookie中_U的值：

`_U=1Cq4jM9233u0kUvAP0N8WTtJOQc4ojtxPJHRDeSuIMAb1wNQMovgGyTyG3ES8ssoSOct4HyBaqj5KKcL2asyfvdT1yJPrHfyXVw08OpHs9n0o67BeMAmHPor1fiGJQtHsWlmE7NBJwvol_RAgSepT4VrMOeOV7DePSpo297NOeaKYAHULIVCVb7600cN1VA40ZG8i2n1HFBiSeJYjF1vwOQ;`

**Comment by cssxsh** [comment]
> 服务器上登录bing吗

可能就是需要服务器上登录一下，因为看样子，微软将 cookie 和 IP 绑定了

**Comment by Krasuszz** [comment]
> > 服务器上登录bing吗
> 
> 可能就是需要服务器上登录一下，因为看样子，微软将 cookie 和 IP 绑定了 因为我拿你这个 cookie 无法在我这边启用

我也是这样猜想的，我需要研究一下无图形界面的服务器怎么登录bing然后再回复这个issue

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-new-bing/releases/tag/v0.2.0

0.2.0 更新了 api

**Comment by Krasuszz** [comment]
> https://github.com/cssxsh/mirai-new-bing/releases/tag/v0.2.0
> 
> 0.2.0 更新了 api， 可能解决你的问题

很完美更新，爱来自瓷器
