### ISSUE TITLE
MiraiNewBingListener: MiraiNewBingListener with 系统代理

### ISSUE THREAD

**Issue by okgo4** [cssxsh/mirai-new-bing#15]
Mirai 版本 2.15.0
插件版本 0.5.0

在执行new bing指令时，系统输出 W/MiraiNewBingListener: MiraiNewBingListener with 系统代理

> io.ktor.client.plugins.ServerResponseException: Server error(GET https://www.bing.com/turing/conversation/create: 200 . Text: "<empty>"
        at mirai-new-bing-0.5.0.mirai2.jar//xyz.cssxsh.bing.NewBingClient.create$suspendImpl(NewBingClient.kt:79)
        at mirai-new-bing-0.5.0.mirai2.jar//xyz.cssxsh.bing.NewBingClient$create$1.invokeSuspend(NewBingClient.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

尝试手动访问网址https://www.bing.com/turing/conversation/create 后返回

> {"conversationId":"51D|BingProd|012EDB6D72621E56F193CD6A4BDC1341F188707ECFEA0286BA638CF4A12D859E","clientId":"985157454971604","conversationSignature":"viK8DlzXCz1hiiakfKKnbrkCyShfOJhmUCLsLFjMoT4=","result":{"value":"Success","message":null}}

请问大佬这是cookie的问题还是微软修改了返回的信息格式orz

**Comment by cssxsh** [comment]
https://github.com/cssxsh/mirai-new-bing/issues/14
