### ISSUE TITLE
使用bing出现错误

### ISSUE THREAD

**Issue by FurLC** [cssxsh/mirai-new-bing#16]
出现报错
`' contains illegal character '
' (code 10)
        at mirai-new-bing-0.5.0.mirai2.jar[private]//io.ktor.http.HttpHeaders.checkHeaderValue(HttpHeaders.kt:160)
        at mirai-new-bing-0.5.0.mirai2.jar[private]//io.ktor.http.HeadersBuilder.validateValue(Headers.kt:41)
        at mirai-new-bing-0.5.0.mirai2.jar[private]//io.ktor.util.StringValuesBuilderImpl.append(StringValues.kt:230)
        at mirai-new-bing-0.5.0.mirai2.jar[private]//io.ktor.client.request.UtilsKt.header(utils.kt:33)
        at mirai-new-bing-0.5.0.mirai2.jar//xyz.cssxsh.bing.NewBingClient.create$suspendImpl(NewBingClient.kt:73)
        at mirai-new-bing-0.5.0.mirai2.jar//xyz.cssxsh.bing.NewBingClient.create(NewBingClient.kt)
        at mirai-new-bing-0.5.0.mirai2.jar//xyz.cssxsh.mirai.bing.MiraiNewBingListener.send(MiraiNewBingListener.kt:159)
        at mirai-new-bing-0.5.0.mirai2.jar//xyz.cssxsh.mirai.bing.MiraiNewBingListener.access$send(MiraiNewBingListener.kt:22)
        at mirai-new-bing-0.5.0.mirai2.jar//xyz.cssxsh.mirai.bing.MiraiNewBingListener$chat$4.invokeSuspend(MiraiNewBingListener.kt:150)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
`

**Comment by cssxsh** [comment]
cookie 有问题

**Comment by FurLC** [comment]
> cookie 有问题

emm，这个cookie是直接在bing.com获取吗，还是在ai界面获取

**Comment by cssxsh** [comment]
从日志来看多了一个空格
另外，这个插件基本没法用的
因为微软加了很多检测，有 cookie 都不行

**Comment by FurLC** [comment]
> 从日志来看多了一个空格 另外，这个插件基本没法用的 因为微软加了很多检测，有 cookie 都不行

明白了谢谢了，对了mirai论坛我这边不知道为啥访问不上了，是什么问题
